import React, {useMemo, useState} from 'react';
import {View} from 'react-native';

import CameraView from './../../components/camera';

import {useAppDispatch} from '../../_app';

type MetaData = {
  label: string;
  question: string;
};
const Camera = () => {
  const dispatch = useAppDispatch();
  const galleryFiles = []; // media ref

  const [metadata, setMetadata] = useState<MetaData>({
    label: 'dear',
    question: 'you',
  });

  const lastCaptureImage = useMemo(() => {
    if (galleryFiles.length) {
      return '';
      // return galleryFiles[0].path;
    }
    return '';
  }, [galleryFiles]);

  return (
    <View style={{flex: 1}}>
      <CameraView
        lastCaptureImage={`file://${lastCaptureImage}`}
        onCapture={media => {
          media.label = metadata.label;
          media.question = metadata.question;

          // insertMedia(media, savedMedia => {
          //   //needing saved image id and id is generated by wmdb so geeting saved record
          //   dispatch(addCapturedImage(savedMedia));
          //   setMetadata(prev => ({...prev, label: ''}));
          // });
        }}
        label={metadata?.label}
      />
    </View>
  );
};

export default Camera;
